// Ghana administrative divisions: Region -> District -> Sub-district.
// Vendored from a Region/District/Sub-district CSV mapping (16 regions,
// 261 districts, 261 districts with sub-district data).
// District names are unique across regions (verified no collisions).

export const GHANA_REGIONS = [
  "Ahafo",
  "Ashanti",
  "Bono",
  "Bono East",
  "Central",
  "Eastern",
  "Greater Accra",
  "North East",
  "Northern",
  "Oti",
  "Savannah",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Western North",
];

export const GHANA_DISTRICTS_BY_REGION = {
  "Ahafo": [
    "Asunafo North",
    "Asunafo South",
    "Asutifi North",
    "Asutifi South",
    "Tano North",
    "Tano South",
  ],
  "Ashanti": [
    "Adansi Akrofuom",
    "Adansi Asokwa",
    "Adansi North",
    "Adansi South",
    "Afigya Kwabre North",
    "Afigya Kwabre South",
    "Ahafo Ano North",
    "Ahafo Ano South East",
    "Ahafo Ano South West",
    "Amansie Central",
    "Amansie South",
    "Amansie West",
    "Asante Akim Central",
    "Asante Akim North",
    "Asante Akim South",
    "Asante Mampong",
    "Asokore Mampong",
    "Asokwa",
    "Atwima Kwanwoma",
    "Atwima Mponua",
    "Atwima Nwabiagya",
    "Atwima Nwabiagya North",
    "Bekwai",
    "Bosome Freho",
    "Bosomtwe",
    "Ejisu",
    "Ejura-Sekyedumase",
    "Juaben",
    "Kumasi",
    "Kwabre East",
    "Kwadaso",
    "Obuasi",
    "Obuasi East",
    "Offinso",
    "Offinso North",
    "Oforikrom",
    "Old Tafo",
    "Sekyere Afram Plains",
    "Sekyere Central",
    "Sekyere East",
    "Sekyere Kumawu",
    "Sekyere South",
    "Suame",
  ],
  "Bono": [
    "Banda",
    "Berekum",
    "Berekum West",
    "Dormaa East",
    "Dormaa Municipal",
    "Dormaa West",
    "Jaman North",
    "Jaman South",
    "Sunyani Municipal",
    "Sunyani West",
    "Tain",
    "Wenchi",
  ],
  "Bono East": [
    "Atebubu-Amanten",
    "Kintampo North",
    "Kintampo South",
    "Nkoranza North",
    "Nkoranza South",
    "Pru",
    "Pru West",
    "Sene East",
    "Sene West",
    "Techiman Municipal",
    "Techiman North",
  ],
  "Central": [
    "Abura-Asebu-Kwamankese",
    "Agona East",
    "Agona West",
    "Ajumako-Enyan-Essiam",
    "Asikuma-Odoben-Brakwa",
    "Assin Foso",
    "Assin North",
    "Assin South",
    "Awutu Senya",
    "Awutu Senya East",
    "Cape Coast",
    "Efutu",
    "Ekumfi",
    "Gomoa Central",
    "Gomoa East",
    "Gomoa West",
    "Komenda-Edna-Eguafo-Abirem",
    "Mfantseman",
    "Twifo Ati Morkwa",
    "Twifo-Hemang Lower Denkyira",
    "Upper Denkyira East",
    "Upper Denkyira West",
  ],
  "Eastern": [
    "Abuakwa North",
    "Abuakwa South",
    "Achiase",
    "Akwapim North",
    "Akwapim South",
    "Akyemansa",
    "Asene Manso Akroso",
    "Asuogyaman",
    "Atiwa East",
    "Atiwa West",
    "Ayensuano",
    "Birim Central",
    "Birim North",
    "Birim South",
    "Denkyembour",
    "Fanteakwa North",
    "Fanteakwa South",
    "Kwaebibirem",
    "Kwahu Afram Plains North",
    "Kwahu Afram Plains South",
    "Kwahu East",
    "Kwahu South",
    "Kwahu West",
    "Lower Manya-Krobo",
    "New Juaben North",
    "New Juaben South",
    "Nsawam-Adoagyiri",
    "Okere",
    "Suhum",
    "Upper Manya-Krobo",
    "Upper West Akim",
    "West Akim",
    "Yilo-Krobo",
  ],
  "Greater Accra": [
    "Ablekuma Central",
    "Ablekuma North",
    "Ablekuma West",
    "Accra Metro",
    "Ada East",
    "Ada West",
    "Adentan",
    "Ashaiman",
    "Ayawaso Central",
    "Ayawaso East",
    "Ayawaso North",
    "Ayawaso West",
    "Ga Central",
    "Ga East",
    "Ga North",
    "Ga South",
    "Ga West",
    "Korle-Klottey",
    "Kpone-Katamanso",
    "Krowor",
    "La-Dade-Kotopon",
    "La-Nkwantanang-Madina",
    "Ledzokuku",
    "Ningo Prampram",
    "Okai Koi North",
    "Shai-Osudoku",
    "Tema",
    "Tema West",
    "Weija-Gbawe",
  ],
  "North East": [
    "Bunkpurugu -Nakpanduri",
    "Chereponi",
    "East Mamprusi",
    "Mamprugu-Moagduri",
    "West Mamprusi",
    "Yunyoo-Nasuan",
  ],
  "Northern": [
    "Gushiegu",
    "Karaga",
    "Kpandai",
    "Kumbungu",
    "Mion",
    "Nanton",
    "Nanumba North",
    "Nanumba South",
    "Saboba",
    "Sagnarigu",
    "Savelugu",
    "Tamale",
    "Tatale-Sangule",
    "Tolon",
    "Yendi",
    "Zabzugu",
  ],
  "Oti": [
    "Biakoye",
    "Guan",
    "Jasikan",
    "Kadjebi",
    "Krachi East",
    "Krachi Nchumuru",
    "Krachi West",
    "Nkwanta North",
    "Nkwanta South",
  ],
  "Savannah": [
    "Bole",
    "Central Gonja",
    "East Gonja",
    "North Gonja",
    "North-East Gonja",
    "Sawla-Tuna-Kalba",
    "West Gonja",
  ],
  "Upper East": [
    "Bawku Municipal",
    "Bawku West",
    "Binduri",
    "Bolgatanga East",
    "Bolgatanga Municipal",
    "Bongo",
    "Builsa North",
    "Builsa South",
    "Garu",
    "Kasena-Nankana",
    "Kasena-Nankana West",
    "Nabdam",
    "Pusiga",
    "Talensi",
    "Tempane",
  ],
  "Upper West": [
    "Daffiama-Bussie-Issa",
    "Jirapa",
    "Lambussie",
    "Lawra",
    "Nadowli-Kaleo",
    "Nandom",
    "Sissala East",
    "Sissala West",
    "Wa East",
    "Wa Municipal",
    "Wa West",
  ],
  "Volta": [
    "Adaklu",
    "Afadjato South",
    "Agortime-Ziope",
    "Akatsi North",
    "Akatsi South",
    "Anloga",
    "Central Tongu",
    "Ho",
    "Ho West",
    "Hohoe",
    "Keta",
    "Ketu North",
    "Ketu South",
    "Kpando",
    "North Dayi",
    "North Tongu",
    "South Dayi",
    "South Tongu",
  ],
  "Western": [
    "Ahanta West",
    "Effia-Kwesimintsim",
    "Ellembelle",
    "Jomoro",
    "Mpohor",
    "Nzema East",
    "Prestea-Huni Valley",
    "Sekondi-Takoradi",
    "Shama",
    "Tarkwa-Nsuaem",
    "Wassa Amenfi Central",
    "Wassa Amenfi East",
    "Wassa Amenfi West",
    "Wassa East",
  ],
  "Western North": [
    "Aowin",
    "Bia East",
    "Bia West",
    "Bibiani-Anhwiaso-Bekwai",
    "Bodi",
    "Juaboso",
    "Sefwi-Akontombra",
    "Sefwi-Wiawso",
    "Suaman",
  ],
};

export const GHANA_SUBDISTRICTS_BY_DISTRICT = {
  "Ablekuma Central": [
    "Abossey Okai/Zongo Junction",
    "Laterbiokorshie/TCL",
    "Mataheko/Russia",
    "Shukura/Zamramaline",
    "Zongo/Zoti",
  ],
  "Ablekuma North": [
    "Awoshie",
    "Darkuman",
    "Kwashieman",
    "Odorkor",
    "South Odorkor",
  ],
  "Ablekuma West": [
    "Agege - Mpoase",
    "Dansoman",
    "Glefe",
    "Shiabu - Gbegbeyise",
  ],
  "Abuakwa North": [
    "Kukurantumi",
    "Osiem",
    "Tafo",
  ],
  "Abuakwa South": [
    "Amanfrom (Abuakwa South)",
    "Apedwa",
    "Asafo (Eastern)",
    "Asiakwa",
    "Bunso",
    "Kibi",
    "Maase",
  ],
  "Abura-Asebu-Kwamankese": [
    "Abakrampa",
    "Abura Dunkwa",
    "Asebu (Abura-Asebu-Kwamankese)",
    "Asuansi",
    "Gyabankrom",
    "Moree",
  ],
  "Accra Metro": [
    "Ablekuma (Accra Metro)",
    "Ashiedu Keteke",
    "Okai Koi South",
  ],
  "Achiase": [
    "Achiase (Achiase)",
    "Akenkausu",
    "Anamase",
    "Aperade",
    "Osoroase",
  ],
  "Ada East": [
    "Ada",
    "Kasseh",
    "Pediatorkope",
  ],
  "Ada West": [
    "Anyamam",
    "Bornikope",
    "Sege",
  ],
  "Adaklu": [
    "Ahunda",
    "Helekpe",
    "Sopa-Torda",
    "Waya",
    "Wumenu",
  ],
  "Adansi Akrofuom": [
    "Akrofuom (Adansi Akrofuom)",
    "Amponyase",
  ],
  "Adansi Asokwa": [
    "Aboabo (Adansi Asokwa)",
    "Anhwiaso",
    "Asokwa (Adansi Asokwa)",
    "Fumso",
  ],
  "Adansi North": [
    "Akrokerri",
    "Dompoase (Adansi North)",
    "Fomena",
    "Wioso (Adansi North)",
  ],
  "Adansi South": [
    "Akutreso",
    "Ataase",
    "New Edubiase",
  ],
  "Adentan": [
    "Gbentanaa",
    "Koose",
    "Nii Ashale",
    "Sutsurunaa",
  ],
  "Afadjato South": [
    "Have",
    "Leklebi",
    "Liati",
    "Logba Tafi",
    "Ve",
    "Weto",
  ],
  "Afigya Kwabre North": [
    "Ahenkro",
    "Boamang",
    "Kyekyewere (Afigya Kwabre North)",
    "Nkwantakese",
    "Tetrem",
  ],
  "Afigya Kwabre South": [
    "Aboabogya",
    "Afrancho",
    "Ankaase",
    "Atimatim",
    "Brofoyedru",
    "Kodie",
  ],
  "Agona East": [
    "Asafo",
    "Duakwa/Mensakrom",
    "Kwanyako",
    "Mankrong",
    "Nsaba",
  ],
  "Agona West": [
    "Abodom",
    "Bobikuma",
    "Nkum",
    "Nyakrom",
    "Otsenkrong",
    "Swedru",
  ],
  "Agortime-Ziope": [
    "Afegame",
    "Keyime",
    "Kpetoe",
    "Sarakope",
    "Ziope",
  ],
  "Ahafo Ano North": [
    "Anyinasuso (Ahafo Ano North)",
    "Betiako",
    "Manfo",
    "Subriso",
    "Tepa",
  ],
  "Ahafo Ano South East": [
    "Biemso",
    "Pokukrom (Ahafo Ano South East)",
    "Sabronum",
  ],
  "Ahafo Ano South West": [
    "Mankranso",
    "Mpasaso",
    "Wioso (Ahafo Ano South West)",
  ],
  "Ahanta West": [
    "Agona (Ahanta West)",
    "Apowa",
    "Dixcove",
    "Princess",
  ],
  "Ajumako-Enyan-Essiam": [
    "Abaasa",
    "Ajumako",
    "Bisease",
    "Nkwantanum",
    "Sunkwa",
  ],
  "Akatsi North": [
    "Agormor",
    "Ave - Dakpa",
    "Ave Afiadenyigbe",
    "Ave Dzalele",
    "Avenu",
  ],
  "Akatsi South": [
    "Akatsi",
    "Avenorpedo",
    "Avenorpeme",
    "Gefia",
    "Wute",
  ],
  "Akwapim North": [
    "Adawso",
    "Akropong (Eastern)",
    "Larteh",
    "Mampong (Akwapim)",
    "Mangoase",
    "Tinkong",
  ],
  "Akwapim South": [
    "Aburi",
    "Berekuso",
    "Obotwere",
    "Pakro",
    "Pokrom",
  ],
  "Akyemansa": [
    "Abenase",
    "Akokoaso",
    "Anyinase",
    "Ayirebi",
    "Brenase",
    "Ofoase (Eastern)",
    "Otwereso",
  ],
  "Amansie Central": [
    "Fena Hia",
    "Fiankoma",
    "Jacobu",
    "Numereso",
    "Tweapease",
  ],
  "Amansie South": [
    "Agroyesum",
    "Edubia",
    "Keniago",
    "Tontokrom",
  ],
  "Amansie West": [
    "Antoakrom",
    "Essuowin",
    "Manso Nkwanta",
  ],
  "Anloga": [
    "Anloga (Anloga)",
    "Anyanui",
    "Shime",
    "Tegbi",
  ],
  "Aowin": [
    "Achimfo (Enchi)",
    "Adjuom",
    "Akontombra Nkwanta",
    "Aquai Allah",
    "Boinso",
    "Enchi",
    "New Gyasikrom",
    "Sewum",
    "Yiwabra",
  ],
  "Asante Akim Central": [
    "Dwease-Praaso",
    "Konongo",
    "Odumase",
    "Patriensa",
  ],
  "Asante Akim North": [
    "Agogo (Ashanti)",
    "Amantenaman",
    "Ananekrom",
    "Juansa",
  ],
  "Asante Akim South": [
    "Banka",
    "Bompata",
    "Juaso",
    "Komeso",
    "Obogu",
    "Ofoase",
  ],
  "Asante Mampong": [
    "Adidwan",
    "Kofiase",
    "Krobo",
    "Mampong (Ashanti)",
    "Yonso",
  ],
  "Asene Manso Akroso": [
    "Akroso",
    "Asene",
    "Asuboa",
    "Asuoso",
    "Attiankama Nkwanta",
    "Badukrom",
    "Eshiem",
    "Manso (Eastern)",
  ],
  "Ashaiman": [
    "Amui Jor",
    "Blakpatsona",
    "Gbemi",
    "Maamomo",
    "Mantseman",
    "Niiman",
    "Tsinai-agber",
  ],
  "Asikuma-Odoben-Brakwa": [
    "Amanfopong",
    "Anhwiam",
    "Asikuma (Asikuma-Odoben-Brakwa)",
    "Bedum",
    "Brakwa",
    "Odoben",
  ],
  "Asokore Mampong": [
    "Aboabo (Asokore Mampong)",
    "Adukrom (Asokore Mampong)",
    "Asawase",
    "Asokore Mampong",
    "Sawaba",
    "Sepe Timpom",
  ],
  "Asokwa": [
    "Ahinsan",
    "Asokwa (Asokwa)",
    "Dompoase (Asokwa)",
    "Gyenase",
    "Kumasi South",
    "Kuwait",
  ],
  "Assin Foso": [
    "Akoti",
    "Awisem",
    "Foso",
    "Nyankomasi",
  ],
  "Assin North": [
    "Akonfudi",
    "Akropong Odumase",
    "Basofi",
    "Bediadua",
    "Bereku",
    "Kushea",
    "Praso (Assin North)",
  ],
  "Assin South": [
    "Anyinabrim (Assin South)",
    "Jakai",
    "Manso (Assin South)",
    "Nsuta (Assin)",
    "Nyankumasi Ahenkro",
    "Ongwa",
  ],
  "Asunafo North": [
    "Akrodie",
    "Asumura",
    "Ayomso",
    "Goaso",
    "Kasapin",
    "Mim",
  ],
  "Asunafo South": [
    "Abuom",
    "Kukuom",
    "Kwapong",
    "Sankore",
  ],
  "Asuogyaman": [
    "Adjena Gyakiti",
    "Akosombo",
    "Akwamufie Apeguso",
    "Anum Boso",
    "Atimpoku",
    "Senchi",
  ],
  "Asutifi North": [
    "Gambia",
    "Goamu-Koforidua",
    "Gyedu",
    "Kenyasi",
  ],
  "Asutifi South": [
    "Acherensua",
    "Dadiesoaba",
    "Hwidiem",
    "Nkaseim",
  ],
  "Atebubu-Amanten": [
    "Amanten",
    "Atebubu",
    "Garadima",
    "Jato Zongo",
    "Kumfia",
    "Nyomoase",
  ],
  "Atiwa East": [
    "Anyinam (Atiwa East)",
    "Enyiresi",
    "Kadewaso",
    "New Jejeti",
    "Sekyere",
  ],
  "Atiwa West": [
    "Abomosu",
    "Akrofufu",
    "Akropong (Atiwa West)",
    "Awenare",
    "Ekorso",
    "Kwabeng",
  ],
  "Atwima Kwanwoma": [
    "Ahenema Kokobeng",
    "Foase",
    "Trabuom",
    "Trede",
  ],
  "Atwima Mponua": [
    "Bayerebon",
    "Gyereso",
    "Kotokuom",
    "Ntobroso",
    "Nyinahin",
    "Saakrom",
    "Sreso",
  ],
  "Atwima Nwabiagya": [
    "Abuakwa",
    "Afari",
    "Asakraka (Atwima Nwabiagya)",
    "Kobeng",
    "Nkawie",
  ],
  "Atwima Nwabiagya North": [
    "Akropong (Atwima Nwabiagya North)",
    "Asuofua",
    "Barekese",
    "Dabaa",
  ],
  "Awutu Senya": [
    "Awutu",
    "Bawjiase",
    "Bontrase",
    "Papaase (Awutu Senya)",
    "Senya Breku",
  ],
  "Awutu Senya East": [
    "Akwelley",
    "Kasoa Main",
    "Kasoa North",
    "Odupong Kpehe",
    "Opeikuma",
  ],
  "Ayawaso Central": [
    "Accra Newtown",
    "Alajo",
    "Kokomlemle",
    "Kotobabi",
  ],
  "Ayawaso East": [
    "Kanda",
    "Nima East",
    "Nima West",
  ],
  "Ayawaso North": [
    "Kwaotsuru",
    "Maamobi East",
    "Maamobi West",
  ],
  "Ayawaso West": [
    "Abelemkpe",
    "Dzorwulu",
    "Legon",
    "Roman Ridge",
    "Westlands",
  ],
  "Ayensuano": [
    "Amanase",
    "Anum Apapam",
    "Asuboi",
    "Coaltar",
    "Dorkrochiwa",
    "Kofi Pare",
    "Kuano",
    "Marfo",
    "Teacher Mante",
  ],
  "Banda": [
    "Banda Ahenkro",
    "Bongase",
    "Dorbor",
    "Sabiye",
  ],
  "Bawku Municipal": [
    "Baribari/Bador",
    "Kuka East",
    "Kuka West",
    "Mognori",
    "North Natinga",
    "South Natinga",
    "Urban West",
  ],
  "Bawku West": [
    "Binaba",
    "Boya/Gbantongo",
    "Sapelliga Googo",
    "Tanga Timonde",
    "Tilli Widnaba",
    "Zebilla North",
    "Zebilla South",
    "Zongoire",
  ],
  "Bekwai": [
    "Bekwai",
    "Dominase (Bekwai)",
    "Kokofu",
    "Kortwia",
  ],
  "Berekum": [
    "Berekum Central",
    "Biadan",
    "Kato",
    "Mpatasie",
    "Zongo (Bono)",
  ],
  "Berekum West": [
    "Botokrom",
    "Jinijini",
    "Koraso",
  ],
  "Bia East": [
    "Adabokrom",
    "Arhinful",
    "Asemnyinakrom",
    "Camp-15",
    "Kaase",
    "Massakrom",
  ],
  "Bia West": [
    "Akaatiso",
    "Essam",
    "Kwesi Nkrumah",
    "Mempeasem",
    "Oseikojokrom",
    "Papaase (Bia West)",
    "Yawmatwa",
  ],
  "Biakoye": [
    "Abotoase",
    "Bowiri",
    "Kwamikrom",
    "Nkonya",
    "Worawora Apesokubi",
  ],
  "Bibiani-Anhwiaso-Bekwai": [
    "Anhwiaso (Western)",
    "Awaso",
    "Bekwai (Western)",
    "Bibiani",
    "Chirano",
  ],
  "Binduri": [
    "Aniisi/Kukparigu",
    "Atuba/Nafkolga",
    "Bazua",
    "Binduri Central",
    "Manga/Goore",
    "Zawse/Bansi",
  ],
  "Birim Central": [
    "Aboabo (Birim Central)",
    "Jamaica",
    "Oda New Town",
    "Oda Nkwanta",
    "Old Town",
  ],
  "Birim North": [
    "Afosu",
    "Akoase",
    "Amuana Praso",
    "New Abirem",
    "Nkwateng",
    "Tweapease (Eastern)",
  ],
  "Birim South": [
    "Aduasa",
    "Akim Swedru",
    "Apoli",
  ],
  "Bodi": [
    "Amoaya",
    "Bodi",
    "Suiano",
  ],
  "Bole": [
    "Bamboi",
    "Bole",
    "Jama",
    "Mandari",
    "Mankuma",
    "Tinga",
  ],
  "Bolgatanga East": [
    "Gambibgo",
    "Katanga",
    "Zuarungu",
    "Zuarungu West",
    "Zuarungu-Moshie",
  ],
  "Bolgatanga Municipal": [
    "Bolga Central",
    "Bolga North",
    "Bolga South",
    "Kalbeo",
    "Plaza",
    "Sherigu",
    "Sumbrungu East",
    "Sumbrungu West",
    "Zaare",
  ],
  "Bongo": [
    "Bongo Beo",
    "Bongo Central",
    "Bongo Soe",
    "Namoo",
    "Valley Zone",
    "Zorko",
  ],
  "Bosome Freho": [
    "Asiwa",
    "Dunkura",
    "Nsuaem",
    "Nsuta (Bosome Freho)",
    "Tebeso",
  ],
  "Bosomtwe": [
    "Amakom",
    "Jachie",
    "Kuntanase",
    "Pramso",
  ],
  "Builsa North": [
    "Chuchuliga",
    "Kadema",
    "Sandema East",
    "Sandema West",
    "Siniensi",
    "Wiaga",
  ],
  "Builsa South": [
    "Doninga",
    "Fumbisi",
    "Gbedema",
    "Kanjarga",
    "Uwasi",
    "Wiesi",
  ],
  "Bunkpurugu -Nakpanduri": [
    "Bimbagu",
    "Binde",
    "Bunkpurugu",
    "Nakpanduri",
  ],
  "Cape Coast": [
    "Adisadel",
    "Cape Coast Central",
    "Efutu",
    "Ewim",
    "UCC",
  ],
  "Central Gonja": [
    "Buipe",
    "Kusawgu",
    "Mpaha",
    "Tulwei",
    "Yala",
    "Yapei",
  ],
  "Central Tongu": [
    "Adidome",
    "Afego",
    "Kpoviadzi Avedo",
    "Mafi Sasekpe",
    "Mafi-Kumase",
  ],
  "Chereponi": [
    "Bumburiga",
    "Chereponi",
    "Garinkuka",
    "Wenchiki",
    "Wonjuga",
  ],
  "Daffiama-Bussie-Issa": [
    "Bussie",
    "Daffiama",
    "Fian",
    "Issa",
    "Kojokperi",
  ],
  "Denkyembour": [
    "Akwatia",
    "Apinamang",
    "Boadua",
    "GCD",
    "Okumaning",
    "Takrowase",
    "Topremang",
  ],
  "Dormaa East": [
    "Dormaa Akwamu",
    "Kyeremasu",
    "Wamanafo",
    "Wamfie",
  ],
  "Dormaa Municipal": [
    "Aboabo (Bono)",
    "Amasu",
    "Asikasu (Dormaa Municipal)",
    "Danyame",
    "Dormaa Ahenkro",
  ],
  "Dormaa West": [
    "Krakrom",
    "Kwabena Dwomokrom",
    "Nkrankwanta",
    "Yaakrom",
  ],
  "East Gonja": [
    "Abrumase",
    "Buma",
    "Kafaba",
    "Kayereso",
    "Makango",
    "Salaga North",
    "Salaga South",
  ],
  "East Mamprusi": [
    "Gambaga",
    "Gbintiri",
    "Langbensi",
    "Nalerigu",
    "Sakogu",
  ],
  "Effia-Kwesimintsim": [
    "Anaji",
    "Apremdo",
    "Effia",
    "Kwesimintim",
    "Whindo",
  ],
  "Efutu": [
    "Essuekyir-Gyahadze",
    "Kojo Beedu North - Low cost",
    "Winneba East",
    "Winneba West",
  ],
  "Ejisu": [
    "Ejisu",
    "Krapa",
    "Onwe",
  ],
  "Ejura-Sekyedumase": [
    "Anyinasu",
    "Babaso",
    "Ejura",
    "Kasei",
    "Kyenkyenkura",
    "Nyamebekyere",
    "Sekyedumase",
  ],
  "Ekumfi": [
    "Essuehyia",
    "Narkwa",
    "Otuam",
  ],
  "Ellembelle": [
    "Aiyinase",
    "Ampain",
    "Asasetre",
    "Eikwe",
    "Esiama",
    "New Aiyinase",
    "Nkroful",
  ],
  "Fanteakwa North": [
    "Abourso",
    "Ahomahomasu",
    "Asirebuso",
    "Begoro North",
    "Begoro South",
    "Dedeso",
  ],
  "Fanteakwa South": [
    "Bosuso",
    "Dwenase",
    "Ehiamankyene (Fanteakwa South)",
    "Nkankama",
    "Osino",
  ],
  "Ga Central": [
    "Ablekuma (Ga Central)",
    "Anyaa",
    "Chantan",
    "Sowutuom",
  ],
  "Ga East": [
    "Abokobi",
    "Ashongman",
    "Dome",
    "Haatso",
    "Taifa",
  ],
  "Ga North": [
    "Amanfrom (Ga North)",
    "Ofankor",
    "Pokuase",
    "Trobu",
  ],
  "Ga South": [
    "Amanfro",
    "Bortianor",
    "Kokrobite",
    "Obom",
  ],
  "Ga West": [
    "Amasaman",
    "Kotoku",
    "Mayera",
    "Oduman",
  ],
  "Garu": [
    "Denugu",
    "Garu",
    "Kpatia",
    "Kpatua",
    "Kugri",
    "Songo",
    "Worikambo",
  ],
  "Gomoa Central": [
    "Aboso (Gomoa Central)",
    "Asebu (Gomoa Central)",
    "Ekwamkrom",
    "Obuasi",
  ],
  "Gomoa East": [
    "Buduatta",
    "Buduburam",
    "Nyanyano",
    "Ojobi",
    "Potsin",
  ],
  "Gomoa West": [
    "Apam",
    "Brofo",
    "Dago",
    "Mumford",
    "Oguaa",
    "Onyadze",
    "Osedze",
  ],
  "Guan": [
    "Akpafu",
    "Likpe Abrani",
    "Likpe Bakwa",
    "Lolobi",
    "Santrokofi",
  ],
  "Gushiegu": [
    "Galwei",
    "Gushiegu",
    "Katani",
    "Kpatinga",
    "Nabuli",
  ],
  "Ho": [
    "Dutasor",
    "Ho Central",
    "Hokpeta",
    "Norvisi",
    "Sokode",
  ],
  "Ho West": [
    "Abutia",
    "Avatime",
    "Kpedze",
    "Tsito",
    "Weto-Hedzefe",
    "Yingor",
  ],
  "Hohoe": [
    "Agumatsa",
    "Alavanyo",
    "Gbi Urban",
    "Hohoe",
  ],
  "Jaman North": [
    "Adadiem",
    "Duadaso",
    "Goka",
    "Sampa",
    "Seketia",
    "Suma",
  ],
  "Jaman South": [
    "Abirikasu",
    "Adamsu",
    "Drobo",
    "Gonasua",
    "Jenjemireja",
    "Zezera",
  ],
  "Jasikan": [
    "Akaa",
    "Baika Ayoma",
    "Bodada",
    "Jasikan",
    "Kute",
    "Nsuta (Buem)",
  ],
  "Jirapa": [
    "Duori",
    "Hain",
    "Jirapa",
    "Sabuli",
    "Tizza",
    "Tuggo",
    "Ullo",
    "Yagha",
  ],
  "Jomoro": [
    "Beyin",
    "Elubo",
    "Half Assini",
    "Newtown",
    "Samaenye",
    "Tikobo No1",
  ],
  "Juaben": [
    "Achiase (Juaben)",
    "Bomfa",
    "Juaben",
  ],
  "Juaboso": [
    "Asempaneye",
    "Bonsu Nkwanta",
    "Jato Africa",
    "Juaboso",
    "Proso- Kofikrom",
    "Sayerano",
  ],
  "Kadjebi": [
    "Ahamansu",
    "Dodi",
    "Dodo",
    "Kadjebi-Asato",
    "Pampawie",
  ],
  "Karaga": [
    "Karaga",
    "Komoayili",
    "Nyong",
    "Pishigu",
    "Sakulo",
    "Sandua",
    "Tong",
    "Zandua",
  ],
  "Kasena-Nankana": [
    "Kologo",
    "Manyoro",
    "Navrongo Central",
    "Navrongo East",
    "Pungu",
    "Vunania/Kapania",
    "Wuru",
  ],
  "Kasena-Nankana West": [
    "Chiana",
    "Kandiga",
    "Katiu Nankong",
    "Kayoro",
    "Mirigu Nabango",
    "Nakolo",
    "Navio",
    "Paga Central",
    "Sirigu Busongo",
  ],
  "Keta": [
    "Anyako",
    "Keta",
  ],
  "Ketu North": [
    "Afife",
    "Devego",
    "Dzodze",
    "Penyi",
    "Tadzewu",
    "Weta",
  ],
  "Ketu South": [
    "Aflao East",
    "Aflao Wego",
    "Aflao West",
    "Klikor",
    "Some Fugo",
    "Some Wego",
  ],
  "Kintampo North": [
    "Busuama",
    "Dawadawa",
    "Gulumpe",
    "Kadelso",
    "Kintampo",
    "Kunsu",
    "New Longoro",
  ],
  "Kintampo South": [
    "Amoma",
    "Anyima",
    "Apesika",
    "Dumso",
    "Jema",
    "Mansie",
  ],
  "Komenda-Edna-Eguafo-Abirem": [
    "Agona",
    "Ankaful",
    "Elmina",
    "Kissi",
    "Komenda",
  ],
  "Korle-Klottey": [
    "Adabraka",
    "North Ridge",
    "Osu",
    "Tema Station",
    "Tudu",
  ],
  "Kpandai": [
    "Kabonwule",
    "Kitare",
    "Kpandai",
    "Kumdi",
    "Sabonjida",
  ],
  "Kpando": [
    "Agbenorxoe",
    "Gbefi-Gadza",
    "Kpando",
    "Sovie-Kudzra",
    "Torkor",
  ],
  "Kpone-Katamanso": [
    "Appolonia",
    "Gbetsile",
    "Kpone",
    "Oyibi",
    "Zenu",
  ],
  "Krachi East": [
    "Dormabin",
    "Island (Krachi East)",
    "Katanga Asukawkaw",
    "Kparekpare",
    "Oti - West",
    "Oti- East",
    "Tokuroanu",
  ],
  "Krachi Nchumuru": [
    "Anyinamae",
    "Banda",
    "Borae",
    "Chayo",
    "Chinderi",
    "Grubi",
  ],
  "Krachi West": [
    "Denteh",
    "Ehiamankyene (Krachi West)",
    "Island(Krachi West)",
    "Osramanae",
  ],
  "Krowor": [
    "Krowor Central",
    "Krowor North",
    "Krowor South",
  ],
  "Kumasi": [
    "Abrepo-Ohwim",
    "Adiembra-Santasi",
    "Ahodwo-Danyame",
    "Bantama-Bohyen",
    "Buokrom-Moshie",
    "Dichemso",
    "Manhyia -Ash Town",
    "Patasi-Suntreso",
    "Subin North",
    "Subin South",
  ],
  "Kumbungu": [
    "Dalun",
    "Gbullung",
    "Gupanerigu",
    "Kumbungu",
    "Voggu",
  ],
  "Kwabre East": [
    "Aboaso",
    "Asonomaso",
    "Kenyase",
    "Mamponteng",
  ],
  "Kwadaso": [
    "Agric-Nzema",
    "Apatrapa- Nyankerenease",
    "Asuoyeboa",
    "Kwadaso Central",
    "Tano-Takyiman",
  ],
  "Kwaebibirem": [
    "Abaam",
    "Abenehease",
    "Asuom",
    "Kade",
    "Otumi",
    "Pramkese",
    "Subi",
    "Takyiman",
  ],
  "Kwahu Afram Plains North": [
    "Abomasarefo",
    "Amankwa",
    "Bruben",
    "Cedikope Island",
    "Digya Island",
    "Donkorkrom Central",
    "Donkorkrom North",
    "Donkorkrom South",
    "Dwarf Island",
    "Faaso Battor",
    "Memchemfre",
    "Ntonaboma",
    "Tsetsekpo",
  ],
  "Kwahu Afram Plains South": [
    "Agyata",
    "Asanyansu",
    "Dim Sakabo",
    "Ekye",
    "Forifori",
    "Kwasi Fante",
    "Mame Krobo",
    "Samanhyia",
    "Tease",
  ],
  "Kwahu East": [
    "Abetifi",
    "Akwasiho",
    "Ankoma",
    "Hweehwee",
    "Kotoso",
    "Kwahu Tafo",
    "Nkwatia",
    "Pepease",
    "Sempoa",
  ],
  "Kwahu South": [
    "Asakraka (Kwahu South)",
    "Bepong",
    "Kwahu Amanfrom",
    "Kwahu Praso",
    "Mpraeso",
    "Nkyenenkyene",
  ],
  "Kwahu West": [
    "Apradang",
    "Asuboni",
    "Aweregya",
    "Danteng",
    "Jejeti",
    "Nkawkaw Amanfrom",
    "Nkawkaw Central",
    "Nkawkaw North",
    "Nkawkaw South",
    "Oframase",
    "Wawase (Kwahu West)",
  ],
  "La-Dade-Kotopon": [
    "La North",
    "La South",
    "Tenashie",
  ],
  "La-Nkwantanang-Madina": [
    "Danfa",
    "Nkwantanang",
    "Pantang",
    "Social Welfare",
    "Tatanaa",
  ],
  "Lambussie": [
    "Billaw",
    "Hamile",
    "Karne",
    "Lambussie",
    "Piina",
    "Samoa",
  ],
  "Lawra": [
    "Babile",
    "Dowine",
    "Eremon",
    "Lawra",
    "Zambo",
  ],
  "Ledzokuku": [
    "Teshie North",
    "Teshie South",
  ],
  "Lower Manya-Krobo": [
    "Agormanya",
    "Akuse",
    "Asitey",
    "Kpong",
    "Oborpa",
    "Odumase (Eastern)",
  ],
  "Mamprugu-Moagduri": [
    "Kubori",
    "Kunkwa",
    "Yagaba",
    "Yikpabongo",
  ],
  "Mfantseman": [
    "Abandze-Kormantse",
    "Anomabo",
    "Biriwa",
    "Dominase (Mfantsiman)",
    "Mankessim",
    "Saltpond",
  ],
  "Mion": [
    "Jimle",
    "Kpabia",
    "Kukpalgu",
    "Sambu",
    "Sang",
  ],
  "Mpohor": [
    "Adansi",
    "Adum Banso",
    "Ayiem",
    "Manso (Mpohor)",
    "Mpohor",
  ],
  "Nabdam": [
    "Nangodi",
    "Pelungu",
    "Pitanga/Kongo",
    "Sakote",
    "Zanlerigu",
  ],
  "Nadowli-Kaleo": [
    "Charikpong",
    "Dapuori",
    "Jang",
    "Kaleo",
    "Nadowli",
    "Nanvilli",
    "Sombo",
    "Takpo",
  ],
  "Nandom": [
    "Baseble",
    "Gengenkpe",
    "Ko",
    "Nandom",
    "Puffien",
  ],
  "Nanton": [
    "Nanton",
    "Tampion",
  ],
  "Nanumba North": [
    "Bimbilla",
    "Bincheratanga",
    "Chamba",
    "Lanja",
    "Makayili",
  ],
  "Nanumba South": [
    "Egambo",
    "Gbungbaliga",
    "Lungni",
    "Napkpayili",
    "Pudua",
    "Wulensi",
  ],
  "New Juaben North": [
    "Akwadum",
    "Asokore (New Juaben North)",
    "Effiduase (Eastern)",
    "Jumapo",
    "Oyoko (New Juaben North)",
  ],
  "New Juaben South": [
    "Adweso",
    "Agavenya",
    "Densuano",
    "Koforidua 1",
    "Koforidua 2",
    "Medical VIllage",
    "Old Estate",
    "Zongo",
  ],
  "Ningo Prampram": [
    "Afienya Mataheko",
    "Dawhenya",
    "Lekpongunor",
    "Nyigbenya Dawa",
    "Old Ningo",
    "Prampram",
  ],
  "Nkoranza North": [
    "Busunya",
    "Dromankese",
    "Kranka",
    "Yefri",
  ],
  "Nkoranza South": [
    "Ahyiayem",
    "Akuma",
    "Ayerede",
    "Bonsu",
    "Donkro Nkwanta",
    "Nkoranza",
    "Nkwabeng",
  ],
  "Nkwanta North": [
    "Damanko",
    "Kpassa",
    "Sibi",
    "Tinjase",
  ],
  "Nkwanta South": [
    "Alokpatsa",
    "Bonakye",
    "Brewaniase",
    "Keri",
    "Nkwanta (Oti)",
    "Tutukpene",
  ],
  "North Dayi": [
    "Anfoega",
    "Aveme",
    "Awate",
    "Botoku",
    "Vakpo",
  ],
  "North Gonja": [
    "Bawena",
    "Daboya",
    "Lingbinsi",
    "Mankarigu",
  ],
  "North Tongu": [
    "Battor",
    "Dorfor-Adidome-Volo",
    "Fodzoku-Torgorme",
    "Juapong-podoe",
    "Mepe",
  ],
  "North-East Gonja": [
    "Bunjai",
    "Jantong",
    "Kpalbe",
    "Kpanshegu",
  ],
  "Nsawam-Adoagyiri": [
    "Adoagyiri",
    "Djankrom",
    "Dobro",
    "Fotobi",
    "Kwakyekrom",
    "Nsawam",
    "Panpanso",
  ],
  "Nzema East": [
    "Axim-Nsein",
    "Bamiankor",
    "Dadwen-Kegyina",
    "Gwira Banso",
    "Gwira Eshiem",
    "Kutukrom",
    "Tebakrom",
  ],
  "Obuasi": [
    "Anyinam (Obuasi)",
    "Gauso",
    "Kunka",
    "New Nsuta",
  ],
  "Obuasi East": [
    "Brahabebome",
    "Kwabrafoso",
    "Tutuka",
  ],
  "Offinso": [
    "Abofour",
    "Anyinasuso (Offinso)",
    "Bonsua",
    "Kwagyekrom",
    "Offinso Central",
  ],
  "Offinso North": [
    "Akumadan",
    "Amponsakrom",
    "Kobreso",
    "Mankramso",
    "Nkenkaasu",
  ],
  "Oforikrom": [
    "Anloga (Oforikrom)",
    "Anwomaso",
    "Ayeduase",
    "KNUST",
  ],
  "Okai Koi North": [
    "Abeka",
    "Achimota",
    "Akweteman",
  ],
  "Okere": [
    "Abiriw",
    "Adukrom (Okere)",
    "Okrakwadjo",
  ],
  "Old Tafo": [
    "Pankrono",
    "Tafo Ahenbronum",
    "Tafo Nhyiaeso",
    "Tafo Zongo",
  ],
  "Prestea-Huni Valley": [
    "Aboso (Prestea-Huni Valley)",
    "Asikuma-(PHV)",
    "Awudua",
    "Bogoso",
    "Bondaye",
    "Damang",
    "Himan",
    "Huni Valley",
    "Insusiding",
    "Prestea",
    "Tarkwa Bremang",
  ],
  "Pru": [
    "Parambo",
    "Yeji",
  ],
  "Pru West": [
    "Abease",
    "Prang",
    "Zabrama",
  ],
  "Pusiga": [
    "Kulungugu/Kultamsi",
    "Nakom Zuabuliga",
    "Pusiga",
    "Sarabogo",
    "Widana",
  ],
  "Saboba": [
    "Gbangbanpong",
    "Kpalba",
    "Natagu",
    "Saboba",
    "Sambuli",
    "Wapuli",
  ],
  "Sagnarigu": [
    "Choggu",
    "Garizegu",
    "Kamina",
    "Malshegu",
    "Sagnarigu",
    "Taha",
  ],
  "Savelugu": [
    "Diare",
    "Moglaa",
    "Pong Tamale",
    "Savelugu",
  ],
  "Sawla-Tuna-Kalba": [
    "Gbiniyiri",
    "Gindabuo",
    "Kalba",
    "Kong",
    "Kulmasah",
    "Kunfusi",
    "Sawla",
    "Tuna",
  ],
  "Sefwi-Akontombra": [
    "Akontombra",
    "Asantekrom",
    "Bawakrom",
    "Kramokrom",
    "Nsawora",
  ],
  "Sefwi-Wiawso": [
    "Abrabra",
    "Anyinabrim (Sefwi-Wiawso)",
    "Asafo (Sefwi-Wiawso)",
    "Asawinso",
    "Datano",
    "Paboase",
    "Wiawso",
  ],
  "Sekondi-Takoradi": [
    "Diabene",
    "Effia Nkwanta",
    "Essikado",
    "Kojokrom (Sekondi-Takoradi)",
    "Kokompe",
    "Sekondi",
    "Takoradi",
  ],
  "Sekyere Afram Plains": [
    "Anyinofi",
    "Dawia",
    "Drobonso",
    "Funsua",
  ],
  "Sekyere Central": [
    "Asubuasu",
    "Birem",
    "Kwamang",
    "Nsuta (Sekyere Central)",
    "Oku",
  ],
  "Sekyere East": [
    "Asokore (Sekyere East)",
    "Effiduase",
    "Mponua",
    "Nyanfa",
  ],
  "Sekyere Kumawu": [
    "Bira Onwam",
    "Kumawu",
    "Oyoko (Sekyere Kumawu)",
    "Woraso",
  ],
  "Sekyere South": [
    "Agona (Sekyere South)",
    "Jamasi",
    "Kona",
    "Wiamoase",
  ],
  "Sene East": [
    "Bassa",
    "Kajaji",
    "Kojokrom (Sene East)",
  ],
  "Sene West": [
    "Bantama (Bono East)",
    "Drobe",
    "Kwame Danso",
    "Kyeamekrom",
    "Lassi",
  ],
  "Shai-Osudoku": [
    "Agomeda",
    "Ayikuma",
    "Dodowa",
    "Duffor",
    "Osudoku",
  ],
  "Shama": [
    "Aboadze Abuesi",
    "Graveldo",
    "Shama",
    "Supomu Dunkwa",
  ],
  "Sissala East": [
    "Kulfuo",
    "Kunchogu",
    "Nabugubelle",
    "Nabulo",
    "Sakai",
    "Tumu",
    "Wellembelle",
  ],
  "Sissala West": [
    "Fielmuo",
    "Gwollu",
    "Jawia",
    "Jeffisi",
    "Zini",
  ],
  "South Dayi": [
    "Duga",
    "Dzake",
    "Kpeve Adzokoe",
    "Peki",
    "Tongor",
  ],
  "South Tongu": [
    "Agorta-Gamenu",
    "Dabala-Adutor",
    "Dordoekope",
    "Dorkploame",
    "Sogakope",
    "Sotewu",
  ],
  "Suaman": [
    "Akoskrom",
    "Dadieso",
    "Karlo",
    "Kwasuo",
  ],
  "Suame": [
    "Bremang",
    "Kronum Aboahia",
    "Suame",
    "Tarkwa Maakro",
  ],
  "Suhum": [
    "Akorabo",
    "Akote",
    "Ayekotse",
    "Kukua",
    "Nankese",
    "Obretema",
    "Sra",
    "Suhum",
    "Supresu",
  ],
  "Sunyani Municipal": [
    "Abesim",
    "Antwikrom",
    "New Dormaa",
    "New Town-bakoniaba",
    "Penkwase",
    "Sunyani Central",
  ],
  "Sunyani West": [
    "Bofourkrom",
    "Chiraa",
    "Fiapre",
    "Nsoatre",
    "Odumase (Bono)",
  ],
  "Tain": [
    "Badu",
    "Debibi",
    "Nsawkaw",
    "Seikwa",
  ],
  "Talensi": [
    "Datoku",
    "Duusi/Gbani",
    "Gorogo",
    "Namolgo/Kpatia",
    "Pwalugu",
    "Shia",
    "Tolla/Nungu",
    "Tongo",
    "Winkongo",
  ],
  "Tamale": [
    "Bilpeila",
    "Nyohini",
    "Tamale Central",
    "Vitting",
  ],
  "Tano North": [
    "Adrobaa",
    "Bomaa",
    "Duayaw Nkwanta",
    "Tanoso",
    "Yamfo",
  ],
  "Tano South": [
    "Bechem",
    "Brosankro",
    "Derma",
    "Techimantia",
  ],
  "Tarkwa-Nsuaem": [
    "Benso",
    "Dompim",
    "Essuoso",
    "Iduapriem",
    "New Atuabo",
    "Nsuaem (Western)",
    "Nsuta (Western)",
    "Simpa",
    "Tarkwa",
  ],
  "Tatale-Sangule": [
    "Kandin",
    "Kparbutabo",
    "Nahuyili",
    "Sangbaa",
    "Sanguli",
    "Tatale",
  ],
  "Techiman Municipal": [
    "Nkwaeso",
    "Nsuta (Techiman)",
    "Oforikrom",
    "Tanoso",
    "Techiman East",
    "Techiman North",
    "Techiman West",
  ],
  "Techiman North": [
    "Aworowa",
    "Buoyem",
    "Krobo",
    "Offuman",
    "Tuobodom",
  ],
  "Tema": [
    "Community 1",
    "Manhean",
    "Tema North",
    "Tema South",
  ],
  "Tema West": [
    "Adjei Kojo",
    "Baatsonaa",
    "Halcrow",
    "Lashibi",
    "Sakumono",
  ],
  "Tempane": [
    "Basyonde",
    "Bugri",
    "Gagbiri",
    "Kpikpira",
    "Tempane",
    "Woriyanga",
  ],
  "Tolon": [
    "Kasuliyili",
    "Kpendua",
    "Lingbunga",
    "Nyankpala",
    "Tolon",
    "Wantugu",
  ],
  "Twifo Ati Morkwa": [
    "Bimpong Egya",
    "Morkwa",
    "Nyinase",
    "Praso (Twifo Ati Morkwa)",
    "Wamaso",
  ],
  "Twifo-Hemang Lower Denkyira": [
    "Frami",
    "Hemang",
    "Jukwa",
    "Wawase (Twifo-Hemang Lower Denkyira)",
  ],
  "Upper Denkyira East": [
    "Asikuma (Upper Denkyira East)",
    "Dunkwa",
    "Imbraim",
    "Kyekyewere (Upper Denkyira East)",
    "Oponso",
    "Pokukrom (Upper Denkyira East)",
  ],
  "Upper Denkyira West": [
    "Ayanfuri",
    "Diaso",
    "Ntom",
    "Subin",
  ],
  "Upper Manya-Krobo": [
    "Akateng",
    "Anyaboni",
    "Asesewa",
    "Dzamam",
    "Otrokper",
    "Sekesua",
    "Sisiamang",
  ],
  "Upper West Akim": [
    "Abamkrom",
    "Adeiso",
    "Asikasu (Upper West Akim)",
    "Asuokaw",
    "Mepom",
    "Nyanoa",
    "Odumkyere Darmang",
    "Okurase",
  ],
  "Wa East": [
    "Baayiri",
    "Bulenga",
    "Funsi",
    "Holomuni",
    "Kundungu",
    "Loggu",
    "Yaala",
  ],
  "Wa Municipal": [
    "Bamahu",
    "Busa",
    "Charia",
    "Charingu",
    "Dobile",
    "Kambali",
    "Kperisi",
    "Kpongu",
    "Wa North",
    "Wa South",
  ],
  "Wa West": [
    "Dorimon",
    "Eggu",
    "Ga",
    "Gurungu",
    "Kukpali-Dabo",
    "Lassia Tuolu",
    "Poyentanga",
    "Vieri",
    "Wechiau",
  ],
  "Wassa Amenfi Central": [
    "Adjakaa Manso",
    "Agona Amenfi",
    "Anakum",
    "Anyinabrim (Wassa Amenfi Central)",
    "Bonsie",
    "Manso Amenfi",
  ],
  "Wassa Amenfi East": [
    "Afransie",
    "Akropong (WAE)",
    "Bawdie",
    "Dawurampong",
    "Mampong (WAE)",
    "Nananko",
    "Oppon Valley",
    "Saa",
  ],
  "Wassa Amenfi West": [
    "Asankran Breman",
    "Asankran-Saa",
    "Asankrangwa",
    "Attobrakrom",
    "Bisaaso",
    "Gravel Yard",
    "Samreboi",
    "Wassa Dunkwa",
  ],
  "Wassa East": [
    "Ateiku",
    "Atobiase",
    "Daboase",
    "Sekyere Krobo",
  ],
  "Weija-Gbawe": [
    "Mallam",
    "Oblogo",
    "Weija",
  ],
  "Wenchi": [
    "Asuogya",
    "Nchiraa",
    "Subinso",
    "Tromeso",
    "Wenchi East",
    "Wenchi West",
  ],
  "West Akim": [
    "Akanteng",
    "Amanfrom (West Akim)",
    "Asamankese",
    "Aworasa",
    "Blue Diamond",
    "Brekumanso",
    "Ekoso Quashie",
    "Osenase",
    "Pabi",
    "Sabong Zongo",
  ],
  "West Gonja": [
    "Busunu",
    "Canteen",
    "Damongo",
    "Dass",
    "Larabanga",
  ],
  "West Mamprusi": [
    "Janga",
    "Kparigu",
    "Kpasenkpe",
    "Nasia",
    "Tinguri",
    "Walewale",
    "Wulugu",
    "Yama-Wungu",
  ],
  "Yendi": [
    "Adibo",
    "Bumbong",
    "Ngani",
    "Yendi Central",
    "Yendi East",
    "Yendi West",
  ],
  "Yilo-Krobo": [
    "Agogo (Eastern)",
    "Boti",
    "Bukunor",
    "Nkurakan",
    "Nsutapong",
    "Somanya East",
    "Somanya West",
  ],
  "Yunyoo-Nasuan": [
    "Gbingbani",
    "Nasuan",
    "Yunyoo",
  ],
  "Zabzugu": [
    "Gortanei",
    "Kukpaligu",
    "Nakpale",
    "Sabare",
    "Zabzugu",
  ],
};
